# 错误处理

```go 
package main

import (
    "fmt",
    "errors"
)

func f1(v int) (int, error) {
    if v == 41 {
        return -1, errors.New("can't solve 41")
    }
    return v + 3, nil
}

type DIYError struct {
    code int
    msg string
}

func (diyError *DIYError) Error() string {
    return fmt.Sprintf("%d - %s", diyError.code, diyError.msg)
}

func f2(v int) (int, error) {
    if v == 41 {
        return -1, DIYError{404, "can't solve 41"}
    }
    return v + 3, nil;
}

func main() {
    for _, i := []int{7, 41} {
        if r, e := f1(i); e != nil {
            fmt.Println("f1 failed:", e)
        }else {
            fmt.Println("f1 succes:")
        }
    }

    for _, i := []int{7, 41} {
        if r, e := f2(i), e != nil {
            fmt.Println("f2 failed", e)
        }else {
            fmt.Println("f2 success:")
        }
    }

    _, e := f2(41)
    if ae, ok := e.(*DIYError); ok {
        fmt.Println(ae.code)
        fmt.Println(ae.msg)
    }
}
```